### PR TITLE
Add chesu@ to drive-content-managers.members.txt

### PR DESCRIPTION
**Pull request by chensun**
/cc @jessiezcc 

/assign @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/220)

### CODE REVIEW

**Comment by jlewi** [comment]
@chensun Could you please explain why you need to be added as a content manager?

Are you willing to help others transfer Google Docs as needed to the public drive?

See kubeflow/community#308

If you are per kubeflow/community#308 could you please open a PR in that repo documenting the process for transferring docs to the public drive and listing yourself as one of the content managers.

Note I think you will need to list your non @google.com email address. You can't use your @google.com address to transfer docs to drives outside the google.com domain.

**Comment by chensun** [comment]
Sorry for the late reply, I thought I have replied this but somehow I didn't post. 

> @chensun Could you please explain why you need to be added as a content manager?
> 

Context: I was trying to move an internal doc to "Kubeflow (public)" drive so it's accessible to our customers, but found out that I didn't have the permission to do so. Eventually, Jessie worked with you and got the permission, so she helped upload the doc. So I think it would be nice if I can get the permission as well, so that in the future 

> Are you willing to help others transfer Google Docs as needed to the public drive?
> 
> See [kubeflow/community#308](https://github.com/kubeflow/community/issues/308)
> 
> If you are per [kubeflow/community#308](https://github.com/kubeflow/community/issues/308) could you please open a PR in that repo documenting the process for transferring docs to the public drive and listing yourself as one of the content managers.
> 

By "others", are you referring to community devs? I didn't think about that, but I'm happy to help. What should the process be like? like who's going to triage what kind of docs can be put in the public drive, is there any quality requirement, etc.

> Note I think you will need to list your non @google.com email address. You can't use your @google.com address to transfer docs to drives outside the google.com domain.

It looks like Jessie used her @google.com email, and she was able to upload the doc. Is there anything we missed by using @google.com account?

**Comment by jlewi** [comment]
Jessie tried her @google.com mail and it didn't work so we added her @kubeflow.org email and that's what worked.

You can use your personal email.

The process is documented in kubeflow/community#308

Basically, we can't/don't want to keep expanding the list of document managers everytime an individual wants to transfer a single document. So instead we'd like the content managers to take on transferring owners it should be pretty lightweight.

**Comment by chensun** [comment]
> Jessie tried her @google.com mail and it didn't work so we added her @kubeflow.org email and that's what worked.
> 
> You can use your personal email.
> 
> The process is documented in [kubeflow/community#308](https://github.com/kubeflow/community/issues/308)
> 
> Basically, we can't/don't want to keep expanding the list of document managers everytime an individual wants to transfer a single document. So instead we'd like the content managers to take on transferring owners it should be pretty lightweight.

Thanks for the clarification, I updated this PR to use my gmail account.
I will open another PR in the community repo shortly to document the process. 

One question: we noticed the doc that Jessie uploaded earlier isn't public accessible. And I've tried a few different docs in the same folder. While I can access some with my gmail account but not all of them. So it looks the the permission is still per doc level, rather than on the folder/driver level. Is there anything we missed?

**Comment by jlewi** [comment]
Jessie's PR didn't work and I created a follow on PR.
https://github.com/kubeflow/internal-acls/blob/7bf5a1860bf4caccb9216de9932c5610f708586f/drive-content-managers.members.txt#L8

It looks like there is a conflict now in the file. 

The public drive should be viewable to everyone in kubeflow-discuss@ so you may have to join that group from your email in order to see the docs.

**Comment by chensun** [comment]
> Jessie's PR didn't work and I created a follow on PR.
> https://github.com/kubeflow/internal-acls/blob/7bf5a1860bf4caccb9216de9932c5610f708586f/drive-content-managers.members.txt#L8
> 
> It looks like there is a conflict now in the file.
> 
> The public drive should be viewable to everyone in kubeflow-discuss@ so you may have to join that group from your email in order to see the docs.

Thank you, Jeremy. I joined kubeflow-discuss@ with my gmail account. And I'm able to view the doc now. 
I accidentally messed up this PR while doing the merge. So I closed this and created a new one.

**Pull request closed without merging**
