### PR TITLE
Add kbthu to member list.

### PR DESCRIPTION
**Pull request by kbthu**
Provide 2-3 links to PRs or other contributions
https://github.com/kubeflow/examples/pull/1035
https://github.com/kubeflow/examples/pull/1037
https://github.com/kubeflow/examples/pull/1044

pytest test_org_yaml.py
==================================================================== test session starts ====================================================================
platform linux -- Python 3.8.10, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/kbthu/internal-acls/github-orgs
collected 1 item

test_org_yaml.py .                                                                                                                                    [100%]

===================================================================== 1 passed in 0.23s =====================================================================

cc: @andreyvelich

### CODE REVIEW

**Comment by kbthu** [comment]
@james-jwu Please help to check if this PR is good, and let me know if I need to upload more info. Thank you.

**Comment by zijianjoy** [comment]
@andreyvelich Hello Andrey, would you like to comment on this PR? Thanks!

**Comment by andreyvelich** [comment]
Thank you for contributing to the Kubeflow examples repository @kbthu!
As I can see, all of your contributions were approved by @js-ts.
@js-ts Would you mind to sponsor @kbthu in this PR to be part of Kubeflow org ?

**Comment by js-ts** [comment]
Yes

**Comment by zijianjoy** [comment]
/lgtm
/approve

Welcome to the community! @kbthu

**Pull request merged**
