### PR TITLE
Add lresende to org

### PR DESCRIPTION
**Pull request by lresende**

### CODE REVIEW

**Comment by zijianjoy** [comment]
Hello @lresende , please share 2 or more PRs you have created in Kubeflow org and ask at least 2 sponsors to support this request. Thank you!

https://github.com/kubeflow/internal-acls#joining-kubeflow-github-organization

**Comment by lresende** [comment]
Previous pull requests:
https://github.com/kubeflow/pipelines/pull/8855
https://github.com/kubeflow/website/pull/2820

Sponsors:
@connor-mccarthy @Tomcli

**Comment by andreyvelich** [comment]
Welcome to the Kubeflow Community @lresende 🎉 
@zijianjoy I am happy to sponsor this request
/lgtm

**Comment by zijianjoy** [comment]
/lgtm
/approve

Welcome to the community!

**Pull request merged**
