### PR TITLE
Jeffwan@ step down and nominate PatrickXYS@ to represent AWS

### PR DESCRIPTION
**Pull request by Jeffwan**
Related to this issue https://github.com/kubeflow/community/pull/461

/cc @kubeflow/aws
/cc @kubeflow/wg-deployment-leads @kubeflow/wg-manifests-leads

### CODE REVIEW

**Comment by PatrickXYS** [comment]
@Jeffwan Thanks for your contributions!

**Comment by Bobgy** [comment]
Do you need LGTMs from @kubeflow/wg-deployment-leads @kubeflow/wg-manifests-leads?
I can approve after their LGTMs.

**Comment by PatrickXYS** [comment]
This has been more than one week, can we move forward?

**Comment by Bobgy** [comment]
/approve
Thanks for reminder

**Pull request merged**
