### PR TITLE
Added as contributor

### PR DESCRIPTION
**Pull request by MaanavD**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/106)

### CODE REVIEW

**Comment by abhi-g** [comment]
@MaanavD Please post links to your github PRs you have contributed to Kubeflow. This helps us document your contributions towards the membership.

**Comment by MaanavD** [comment]
> @MaanavD Please post links to your github PRs you have contributed to Kubeflow. This helps us document your contributions towards the membership.

Hi there, here is a PR that I have added. I'm working towards making more in the near future as well.
https://github.com/kubeflow/website/pull/763

**Pull request merged**
