### PR TITLE
Adding nakfour from redhat to org

### PR DESCRIPTION
**Pull request by nakfour**

### CODE REVIEW

**Comment by nakfour** [comment]
Thanks @Bobgy done.

**Comment by Bobgy** [comment]
Can you also list some of your contributions to kubeflow? And which kubeflow members can sponsor for you?

**Comment by nakfour** [comment]
Hi @Bobgy 
Kubeflow Openshift documentation PR https://github.com/kubeflow/website/pull/2146
KF Pipeline issues: https://github.com/kubeflow/pipelines/issues/3322, https://github.com/kubeflow/pipelines/issues/1501
https://github.com/kubeflow/pipelines/issues/4326
KF Seldon: https://github.com/kubeflow/manifests/pull/893
KF Pytorch: https://github.com/kubeflow/manifests/pull/892
KF kubeflow-discuss: https://groups.google.com/g/kubeflow-discuss/search?q=nakfour

KF Members that can sponsor me:  @pdmack @crobby @vpavlin

**Comment by Bobgy** [comment]
Thank you for the contributions!
Welcome to Kubeflow
/lgtm
/approve

**Pull request merged**
