### PR TITLE
Add kromanow94 as member

### PR DESCRIPTION
**Pull request by kromanow94**
Contributions:
* https://github.com/kubeflow/manifests/pull/2544
* https://github.com/kubeflow/manifests/pull/2588
* https://github.com/kubeflow/manifests/issues/2516
* https://github.com/kubeflow/manifests/issues/2517
* https://github.com/kubeflow/manifests/pull/2229#pullrequestreview-1799825164
* https://github.com/kubeflow/kubeflow/issues/7437#issuecomment-1874069314
* https://kubeflow.slack.com/archives/CKBA5D0MU/p1702465109437099
* https://kubeflow.slack.com/archives/C01A7RYEYMB/p1702556772959959
* https://kubeflow.slack.com/archives/CE10KS9M4/p1700672066110009
* https://kubeflow.slack.com/archives/CE10KS9M4/p1700672066110009

pytest output:
```
jovyan@romanok1-0:~/work/kubeflow/internal-acls/github-orgs$ pytest test_org_yaml.py
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.10.6, pytest-7.4.1, pluggy-1.3.0
rootdir: /home/jovyan/work/kubeflow/internal-acls/github-orgs
collected 1 item                                                                                                                                                                   

test_org_yaml.py .                                                                                                                                                           [100%]

================================================================================ 1 passed in 0.18s =================================================================================
```

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
@zijianjoy we need him for Kubeflow 1.9. I cannot set him as owner for Dex etc. if he is not a member.

**Comment by zijianjoy** [comment]
/approve

Welcome @kromanow94 to the community!

**Comment by kromanow94** [comment]
Awesome!

**Pull request merged**
