### PR TITLE
add theofpa as github-org member

### PR DESCRIPTION
**Pull request by theofpa**

### CODE REVIEW

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
Could you list your contributions?

**Comment by theofpa** [comment]
@terrytangyuan I'm active in #aws and #kfserving on slack and [stackoverflow](https://stackoverflow.com/questions/60787646/kubeflow-vs-other-options). Contributed the [aws-e2e guide](https://www.kubeflow.org/docs/aws/aws-e2e/) during the last docsprint, also some changes in [manifests](https://github.com/kubeflow/manifests/pulls?q=is%3Apr+theofpa+is%3Aclosed) and [kfserving](https://github.com/kubeflow/kfserving/pull/814). Maybe @kubeflow-bot can gather such [metrics](https://github.com/kubeflow/community/issues/340) from [devstats](http://devstats.kubeflow.org/d/9/developers-summary?orgId=1) and github to support such discussions in the future.

**Review by terrytangyuan — APPROVED** [review]
Thanks.

/lgtm

**Pull request merged**
