### PR TITLE
A new release team member - Tester

### PR DESCRIPTION
**Pull request by tombuuz**
Joining a tester to the Kubeflow release team 
(Ldagvanorov@gmail.com)

### CODE REVIEW

**Comment by rimolive** [comment]
According to [devstats.io](https://kubeflow.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1), @tombuuz made at least 2 contributions to Kubeflow. That said, he should be eligible to become a member.

Also, since he volunteered to be part of the 1.10 Release Team, I believe he can make more contributions to the community. I'm good to have him added to the GitHub org.

@tombuuz Can you add in the PR description the contributions you made?

**Comment by andreyvelich** [comment]
I think, before updating the release team, we should establish the 1.10 release team with release managers and liaisons. 
Also, you can't update the GitHub teams with users who are not member of Kubeflow GitHub org.

**Comment by rimolive** [comment]
@andreyvelich @terrytangyuan Release Team is formed. Can you please approve his membership?

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/approve

**Review by tombuuz — COMMENTED** [review]
- Add the github username to join the Release team

**Pull request merged**
