### PR TITLE
add grobbie as member of kubeflow org

### PR DESCRIPTION
**Pull request by grobbie**
Hello

Please consider adding me as a member of the Kubeflow organisation and representative for Canonical, thanks.

Sponsors - @DnPlas, @DomFleischmann
PRs - https://github.com/kubeflow/website/pull/3148

### CODE REVIEW

**Comment by grobbie** [comment]
Hi @chensun, the problem is that I'm taking over from @RFMVasconcelos on behalf of Canonical, as owner of the Canonical distribution documentation pages on the website, without org membership I cannot take ownership of these pages.

**Comment by chensun** [comment]
> Hi @chensun, the problem is that I'm taking over from @RFMVasconcelos on behalf of Canonical, as owner of the Canonical distribution documentation pages on the website, without org membership I cannot take ownership of these pages.

I see. Sounds good to me then. Thanks!

/lgtm
/approve

**Pull request merged**
