### PR TITLE
Remove deprecated github teams

### LINKED ISSUE #403: Clean up deprecated github team
Given some GitHub team we established previously is not in use or deprecated,

the list of data points I can collect:

1. @kubeflow/kfctl-release  
2. @kubeflow/project-maintainers 
3. @kubeflow/release-planning 

We should clean up those deprecated github team to formalize permission granting, given now we have WG, which should be folks who have write access to the repo, only a few other folks should have write access to the repo, e.g, release-team, google-admins, etc.

/cc @Bobgy @Jeffwan @jlewi

### PR DESCRIPTION
**Pull request by PatrickXYS**
Resolves #403 

/cc @Jeffwan @Bobgy @kubeflow/wg-deployment-leads

### CODE REVIEW

**Comment by Jeffwan** [comment]
Let's make sure members in these team accept the change.

**Comment by Bobgy** [comment]
/lgtm
Can you ping members in this PR?

**Comment by PatrickXYS** [comment]
/cc @kubeflow/kfctl-release @kubeflow/release-planning @kubeflow/project-maintainers 

Can you take a look?

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by Bobgy** [comment]
/approve
I think we get enough lgtms

**Comment by PatrickXYS** [comment]
/unhold 

Unhold to get it merged

**Pull request merged**
