### PR TITLE
added my githubID in the member's list

### PR DESCRIPTION
**Pull request by Gaurang10**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/199)

### CODE REVIEW

**Comment by jlewi** [comment]
Thanks @Gaurang10 can you point to some of your PRs?

**Comment by Gaurang10** [comment]
This is first time I am trying to contribute to an open source project.

**Comment by jlewi** [comment]
That's great. Have you seen our contributor guide?
https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org

We generally ask you to submit a couple of PRs first before joining the GitHub org.

**Comment by Gaurang10** [comment]
Oh.. I missed it. Let me try to find some issues to raise PR. Thanks.

**Comment by jlewi** [comment]
Thank you. I'll close this PR for now. Feel free to reopen later on after submitting some PRs.

**Pull request closed without merging**
