### PR TITLE
add evilnick to members

### PR DESCRIPTION
**Pull request by evilnick**
Some of my previous contributions:
 
https://github.com/kubeflow/website/pull/2313
https://github.com/kubeflow/website/pull/2274
https://github.com/kubeflow/website/pull/2273
https://github.com/kubeflow/website/pull/2197

Sponsors: @knkski @RFMVasconcelos 

Output from test:
```
$ pytest test_org_yaml.py
====================================================== test session starts ======================================================
platform linux2 -- Python 2.7.18, pytest-4.6.9, py-1.8.1, pluggy-0.13.0
rootdir: /home/evilnick/Canonical/internal-acls/github-orgs
collected 1 item                                                                                                                

test_org_yaml.py .                                                                                                        [100%]

=================================================== 1 passed in 0.19 seconds ====================================================
```

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
@Bobgy, @evilnick is our Kubernetes documentation expert, we've pinged him to help us out in Kubeflow. Could you please allow him to join?

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you for your contributions!
Welcome to Kubeflow!

**Comment by RFMVasconcelos** [comment]
Thank you @Bobgy !!

**Pull request merged**
