### PR TITLE
Add a member from IBM team

### PR DESCRIPTION
**Pull request by xauthulei**
/cc @jinchihe , @jlewi , I wish to work as member is this great open repo.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/135)

### CODE REVIEW

**Comment by jinchihe** [comment]
Thanks @xauthulei 

/assign @jlewi

**Comment by jlewi** [comment]
/lgmt
/approve

Thanks @xauthulei After this PR is merged; please wait an hour for an invite to join the org. If you don't receive an invite after an hour please open an issue.

**Comment by xauthulei** [comment]
Thanks @jinchihe and @jlewi , now I have joined our org.

**Pull request merged**
