### PR TITLE
Setup permissions on project kf-feast.

### PR DESCRIPTION
**Pull request by jlewi**
* This project will be used by the folks at GoJek and Google PSO to
  develop and test feast.

Related to kubeflow/testing#254

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/37)

### CODE REVIEW

**Comment by jlewi** [comment]
@woop can you review and "/lgtm" please?

**Comment by woop** [comment]
Thanks, seems fine.

/lgtm

**Comment by r2d4** [comment]
Looks like you have a merge conflict though

**Comment by jlewi** [comment]
@r2d4 Thanks could you PTAL.

**Pull request merged**
