### PR TITLE
Adding nachocano as a new member

### PR DESCRIPTION
**Pull request by nachocano**
I recently joined a team in Google working on parts of Kubeflow. Was told to add myself to the list

### CODE REVIEW

**Comment by Bobgy** [comment]
Welcome onboard!
/lgtm
/approve
@nachocano Can you resolve the merge conflict?

**Comment by nachocano** [comment]
> Welcome onboard!
> /lgtm
> /approve
> @nachocano Can you resolve the merge conflict?

Done, thanks @Bobgy

**Pull request merged**
