### PR TITLE
Update org.yaml

### PR DESCRIPTION
**Pull request by ccarpentiere**
Add ccarpentiere as a member to help with content reviews.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/116)

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @jlewi 

@ccarpentiere Sorry for the delay? Have you already made some contributions to Kubeflow if so could you link 2-3 to this issue?

**Comment by ccarpentiere** [comment]
I don't have any contributions. I was just signing up so I could help with PR review during the doc sprint (I'm on the same doc team as sarahmaddox). I think it isn't urgent that I have access right now, so if it is a problem that I don't have existing contributions, let me know and I'll close the PR. I can always submit another if needed.

**Comment by jlewi** [comment]
@ccarpentiere Thanks if your on @sarahmaddox 's team that's good enough.

/lgtm
/approve

Once the PR is merged you should get an invite emailed to you; if not please an open an issue because it means the org sync is broken.

**Pull request merged**
