### PR TITLE
Add c-bata to kubeflow org as a member

### PR DESCRIPTION
**Pull request by c-bata**
I started to contribute to Katib.

ScreenShot 2020-03-24 15 58 18

### CODE REVIEW

**Comment by gaocegege** [comment]
/ok-to-test

/lgtm

Contributions: https://github.com/kubeflow/katib/pulls?q=author%3Ac-bata+

**Comment by c-bata** [comment]
Hi @abhi-g! Could you review this PR?

ScreenShot 2020-04-09 18 29 09

**Comment by abhi-g** [comment]
Thanks @c-bata for your contributions.

/approve

**Pull request merged**
