### PR TITLE
Add xieydd to the Kubeflow Member

### PR DESCRIPTION
**Pull request by xieydd**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/31)

### CODE REVIEW

**Comment by xieydd** [comment]
@jlewi pls help to review this PR, Thx.

**Comment by xieydd** [comment]
@abhi-g Done, Thanks for your review.

**Comment by xieydd** [comment]
@abhi-g I notice the PR is merged, but i did`t receive the inventation of the org. 😝

**Comment by abhi-g** [comment]
I'll send you one. Sorry been traveling..

**Pull request merged**
