### PR TITLE
adding jpza to org

### PR DESCRIPTION
**Pull request by jpza**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/72)

### CODE REVIEW

**Comment by jlewi** [comment]
Have you already contributed to Kubeflow?
We typically ask folks to contribute before joining the GitHub org since the primary reason to join is help contribute (e.g. be able to trigger tests, be assigned issues) etc...

**Comment by jpza** [comment]
Commit immanent

**Comment by jlewi** [comment]
Can you link to the PR?

**Comment by jpza** [comment]
Bah, not ready yet. Will reopen after PR is submitted

**Pull request closed without merging**
