### PR TITLE
add varodrig as member to kubeflow org

### PR DESCRIPTION
**Pull request by varodrig**
Resolve: https://github.com/kubeflow/internal-acls/issues/710

Contributions
PRs:
https://github.com/kubeflow/website/pull/3878
https://github.com/kubeflow/website/pull/3899
https://github.com/kubeflow/website/pull/3901

Issues created:
https://github.com/kubeflow/website/issues/3900

pytest output:
image

### CODE REVIEW

**Comment by varodrig** [comment]
@hbelmiro @rimolive

**Review by hbelmiro — COMMENTED** [review]
I'm happy to sponsor this membership.

/lgtm
/ok-to-test

**Comment by varodrig** [comment]
waiting for @rimolive

**Comment by rimolive** [comment]
+1

/lgtm

**Comment by hbelmiro** [comment]
cc @terrytangyuan

**Review by terrytangyuan — APPROVED** [review]
/approve

**Pull request merged**
