### PR TITLE
Add rimolive as member

### PR DESCRIPTION
**Pull request by rimolive**
Refer to #627 

Contributed issues:
https://github.com/kubeflow/kfp-tekton/pull/977
https://github.com/kubeflow/kfp-tekton/pull/1378

pytest output:
```
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.11.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/rmartine/Development/github-projects/internal-acls/github-orgs
plugins: forked-1.6.0, cov-3.0.0, xdist-2.5.0
collected 1 item                                                                                                                                                                   

test_org_yaml.py .                                                                                                                                                           [100%]

================================================================================ 1 passed in 0.09s =================================================================================
```

### CODE REVIEW

**Review by yhwang — APPROVED** [review]
/lgtm

**Comment by Tomcli** [comment]
/lgtm
I'm sponsoring @rimolive to be part of the Kubeflow members.

**Review by chensun — APPROVED** [review]

**Comment by yhwang** [comment]
thanks @chensun  and @rimolive

**Pull request merged**
