### PR TITLE
Add rawc0der as member

### PR DESCRIPTION
**Pull request by rawc0der**
Links to PRs:
- https://github.com/kubeflow/manifests/pull/2457
- https://github.com/kubeflow/pipelines/pull/10087
- https://github.com/argoflow/argoflow/pull/160

Issues, misc:
- https://github.com/kserve/kserve/issues/2643
- https://github.com/argoproj/argo-cd/issues/5614

Pytest output:
```
$ pytest test_org_yaml.py                                                              

================================================= test session starts =================================================
platform darwin -- Python 3.9.18, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /Users/alinspinu/Documents/RawDataLabs/GitHub/internal-acls/github-orgs
collected 1 item                                                                                                      

test_org_yaml.py .                                                                                              [100%]

================================================== 1 passed in 0.21s ==================================================
```

### CODE REVIEW

**Comment by rawc0der** [comment]
Hi @juliusvonkohout and @kimwnasptd, would you be able to become my sponsors? 

Thanks!

**Comment by juliusvonkohout** [comment]
In general yes, but I think there should be at least one merged PR. Currently there are only drafts or open ones as far as I can see. I just reran the tests for the pipelines PR, but I think you need to follow up in the KFP meetings to get it merged. You can also see that we only have 8 open PRs now in kubeflow/manifests (before 50). The network policies are not forgotten ;-)

**Comment by juliusvonkohout** [comment]
And it's definitely possible, I just got @kromanow94 merged in

https://github.com/kubeflow/internal-acls/commit/89d844f78328fe43ef41b64d9237b70f1f2eb688

**Comment by juliusvonkohout** [comment]
After addressing the issues above you can ping @zijianjoy here and on slack (James Liu) to merge.

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Pull request merged**
