### PR TITLE
Turn on unittests

### PR DESCRIPTION
**Pull request by jlewi**
Fixes https://github.com/kubeflow/internal-acls/issues/346
* Run python unittests on presubmit. This way we run the test
  to validate the config.

### CODE REVIEW

**Comment by jlewi** [comment]
This is blocked on the fixes to the python unittests mentioned in
https://github.com/kubeflow/testing/issues/769

**Comment by Bobgy** [comment]
@jlewi can you turn this into a non-draft? thanks!

**Comment by jlewi** [comment]
@Bobgy Sorry done.

**Pull request merged**
