### PR TITLE
Add jiahaoc1993 as kubeflow org member

### PR DESCRIPTION
**Pull request by jiahaoc1993**
Signed-off-by: jiahaoc <jiahaoc@vmware.com>

### CODE REVIEW

**Comment by jiahaoc1993** [comment]
hi, I am one of the contributor of the fate-operator. Since the [proposal](https://github.com/kubeflow/community/pull/335) have been accepted recently, and the [fate-operator repo](https://github.com/kubeflow/fate-operator) is ready right now. So I am asking for your approval to add my account as the kubeflow member so that I can push code the the repo mentioned above.

**Comment by gaocegege** [comment]
> `/aprpove`

Typo here 😄

**Comment by jiahaoc1993** [comment]
Add two person since they are also the contributors of the fate-operator

**Comment by gaocegege** [comment]
Hi seems that @jiahaoc1993 is not invited although the PR is merged, can you help us? @jlewi

**Pull request merged**
