### PR TITLE
Add Jian He to the member

### PR DESCRIPTION
**Pull request by jian-he**
contributing to kubeflow/common and kubeflow/tf-operator in the past

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/91)

### CODE REVIEW

**Comment by abhi-g** [comment]
@jian-he Can you please add links to a couple of PRs you have submitted to Kubeflow.

**Comment by jian-he** [comment]
@abhi-g 

https://github.com/kubeflow/common/commit/a1d9ac2e76d0b5a300e663770878f06b6c7238e8
https://github.com/kubeflow/common/commit/ba975e81270f0133495d11187bbead3b27f0a7ec

**Pull request merged**
