### PR TITLE
Add @ScrapCodes to the ORG !

### PR DESCRIPTION
**Pull request by ScrapCodes**
Merged PRs:

https://github.com/kubeflow/kfp-tekton/pull/602
https://github.com/kubeflow/kfp-tekton/pull/468
https://github.com/kubeflow/kfp-tekton/pull/483
https://github.com/kubeflow/kfp-tekton/pull/500
https://github.com/kubeflow/kfp-tekton/pull/464
https://github.com/kubeflow/pipelines/pull/5212
https://github.com/kubeflow/website/pull/2530

/cc @Tomcli

### CODE REVIEW

**Comment by Tomcli** [comment]
thanks @ScrapCodes 
/lgtm

**Comment by animeshsingh** [comment]
thanks @ScrapCodes for contributions!!

@Bobgy please approve this

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you for your contributions!
Welcome to Kubeflow!

**Comment by ScrapCodes** [comment]
Thank you @animeshsingh for facilitating!
Thank you @Bobgy, @Tomcli !

**Pull request merged**
