### PR TITLE
Add VaniHaripriya as a Kubeflow Member

### PR DESCRIPTION
**Pull request by VaniHaripriya**
Resolves [#719 ](https://github.com/kubeflow/internal-acls/issues/719)

**Contributions**

- https://github.com/kubeflow/pipelines/pull/11300
- https://github.com/kubeflow/pipelines/pull/11295
- https://github.com/kubeflow/pipelines/pull/11262
- https://github.com/kubeflow/pipelines/pull/11066

pytest Output:
```
$ pytest test_org_yaml.py
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.11.9, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/vmudadla/OpenshiftAI/internal-acls/github-orgs
collected 1 item                                                                                                                                                                                                                             

test_org_yaml.py .                                                                                                                                                                                                                     [100%]

============================================================================================================= 1 passed in 0.15s ==============================================================================================================

```

### CODE REVIEW

**Comment by DharmitD** [comment]
Make sure to sign off your commit @VaniHaripriya :)

**Review by hbelmiro — COMMENTED** [review]
I'm happy to endorse Vani's membership.
/lgtm

**Comment by hbelmiro** [comment]
cc @terrytangyuan

**Review by terrytangyuan — APPROVED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
