### PR TITLE
add shinytang6 to kubeflow member

### PR DESCRIPTION
**Pull request by shinytang6**
Would like to join the org and contribute more :)
My previous contributions:
[https://github.com/kubeflow/common/pull/116](https://github.com/kubeflow/common/pull/116)

/cc @gaocegege

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you for your contributions!
Welcome to Kubeflow!

**Pull request merged**
