### PR TITLE
Update org.yaml

### PR DESCRIPTION
**Pull request by danielsiwiec**

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Could you share a list of your contributions?

**Comment by danielsiwiec** [comment]
@terrytangyuan I just made this PR to resolve a typo in one of the sample notebooks kubeflow/metadata#242

**Comment by terrytangyuan** [comment]
Thanks. It would be great to see more contributions before we add you as a member. Feel free to ping here when you are ready. Looking forward to seeing your contributions!

**Comment by danielsiwiec** [comment]
@terrytangyuan ah, I see. I was just following the contributor's guide [here](https://www.kubeflow.org/docs/about/contributing/). would be helpful to make it clear, that it's not needed for every PR. thanks!

**Pull request closed without merging**
