### PR TITLE
Update github release team with 1.5 members

### PR DESCRIPTION
**Pull request by annajung**
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>

- Update GitHub release team members with 1.5 release team members

cc @kimwnasptd @shannonbradshaw @jbottum

### CODE REVIEW

**Comment by kimwnasptd** [comment]
Thanks for the PR Anna!

/lgtm

**Comment by thesuperzapper** [comment]
/hold

As one of the @kubeflow/wg-notebooks-leads, I would like to formally object to the formation of the release team as proposed, on the grounds that it is not acceptable for 75% of the release team to be from a single company.

###  I have raised https://github.com/kubeflow/community/issues/540 track establishing the Kubeflow 1.5 release team in a neutral way that is endourced by the Working Groups and @kubeflow/project-steering-group.

**Comment by annajung** [comment]
The formation of the 1.5 release team has been [finalized](https://groups.google.com/g/kubeflow-discuss/c/KDTXp49Mk48/m/5uyBAgDACAAJ).

The list of members for the 1.5 release team are
@annajung @DomFleischmann @DnPlas @jbottum @Bhakti087 @thesuperzapper @surajkota @js-ts

PR has been updated to reflect the final members except for @Bhakti087 who is not a member of the kubeflow org.

**Comment by kimwnasptd** [comment]
Thanks Anna!

/lgtm

**Comment by thesuperzapper** [comment]
@Bobgy @zijianjoy as much as I love getting write access to repos, I am not sure everyone on the release team needs to be made GitHub writers on `kubeflow`/`manifests`/`website`.

Adding a large number of people to unrestricted write access (outside of PRs), poses quite a bit of risk.

**Comment by kimwnasptd** [comment]
@thesuperzapper sounds good to me as well. This way we both have an easy way to group people and limit the permissions.

Until this point the only reason we needed to have write permissions was to create the release branches and tags in the repos.

**Comment by annajung** [comment]
+1 to @thesuperzapper's proposed solution 

I'll add this to agenda for the next release team meeting and we can discuss it then before closing it out.

**Comment by annajung** [comment]
Based on [Dec 13th 2021 release team meeting](arrik.to/kf-release-team-notes), the release team has decided to remove write access from the "release-team" GitHub team and create a new team "release-managers" to limit write access (PR https://github.com/kubeflow/internal-acls/pull/517).

Both are ready for review
/hold cancel

**Comment by thesuperzapper** [comment]
@zijianjoy can we please get this merged ASAP, as right now people have more access than they should (write access to the repos).

Please also merge https://github.com/kubeflow/internal-acls/pull/517, to give the small number of people who need write access from the release team.

**Comment by zijianjoy** [comment]
/lgtm
/approve

Approving the changes for release-team based on the permission granting of release-team-managers team

**Pull request merged**
