### PR TITLE
Added name/email to .yaml files

### PR DESCRIPTION
**Pull request by alinakuz**
Added email and name to become  member of the Kubeflow organization, Google team, and pipelines team. Also added email to ci-team.yaml.

### CODE REVIEW

**Comment by Bobgy** [comment]
Hi @alinakuz!
Welcome onboard!

Can you clean up the github-orgs/.DS_Store files?

**Comment by alinakuz** [comment]
Hi! And thank you!

I just removed the DS_Store files!

**Comment by Bobgy** [comment]
/lgtm
/approve
Welcome to Kubeflow!

**Pull request merged**
