### PR TITLE
Added Jeff to project maintainers group

### PR DESCRIPTION
**Pull request by elviraux**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/188)

### CODE REVIEW

**Comment by jlewi** [comment]
@elviraux @jtfogarty could you provide some context please? The project group currently provides rather broad permissions on the repos because that's whats required in order to add issues to kanban boards. (See kubeflow/community#250).

What permissions do you need and for what purpose?

**Comment by jtfogarty** [comment]
@jlewi I'm looking to help triage issues.  Whatever the minimum permissions to allow this is all I need

**Comment by jlewi** [comment]
@elviraux and @jtfogarty I created kubeflow/community#314 to try to explain the problem and outline some possible solutions. Could you take a look and maybe come up with a proposal?

@jtfogarty as a stop gap you should be able to add area and kind labels to issues just by using the "/area" and "/kind" commands in issues.

**Comment by jbottum** [comment]
@jlewi just worked with Jeff.   He does not have permissions to triage.   We could really benefit from his help and expertise.   Can we please figure out a way to get him operational ?

**Comment by jlewi** [comment]
@jtfogarty it looks like you are not a member of the Kubeflow org. This explains why 

1. The prow commands "/area" and "/kind" don't work.

@jtfogarty could you please open up PR adding yourself to the GitHub org.

**Pull request closed without merging**
