### PR TITLE
Add my email in the google_groups/groups/example-maintainers.yaml file

### PR DESCRIPTION
**Pull request by js-ts**
Adding My email to the [example-maintainers file](https://github.com/kubeflow/internal-acls/blob/master/google_groups/groups/example-maintainers.yaml)

I'm a maintainer of https://github.com/kubeflow/examples/
OWNER FILE: https://github.com/kubeflow/examples/blob/master/OWNERS

### CODE REVIEW

**Comment by zijianjoy** [comment]
What is the effect of making this change? It seems that you already have permission to manage `examples` repo.

**Comment by js-ts** [comment]
@zijianjoy It has something to do with gcloud or google groups as in this [PR](https://github.com/kubeflow/internal-acls/pull/133)
, please correct me if I'm wrong , I will close the the PR if its unnecessary or it will break things, thanks for reviewing it

**Comment by zijianjoy** [comment]
Based on my observation, it seems to be related to Google groups. However, I don't have access to the group with the name in this file. It is probably because I am not part of the group, and I am not sure how it is being used (or how gcloud is using it). 

@jinchihe You are in the group, would you like to explain what is this file used for? Are we still using it? Thank you!

**Comment by js-ts** [comment]
@zijianjoy  @jinchihe  said me that its useless so I'm closing this PR thanks for reviewing it.

**Pull request closed without merging**
