### PR TITLE
Add DomFleischmann to kubeflow org

### PR DESCRIPTION
**Pull request by DomFleischmann**

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Could you please provide links to your contributions? Thanks

**Comment by DomFleischmann** [comment]
> Could you please provide links to your contributions? Thanks

My first contribution is this one which is still pending for merge: https://github.com/kubeflow/katib/pull/1426

**Comment by terrytangyuan** [comment]
Thank you for your contributions but we'd probably want to wait until we see more contributions. Please keep up the good work!

**Comment by andreyvelich** [comment]
@terrytangyuan It seems that @DomFleischmann recently joined @RFMVasconcelos team and will work on JuJu operators for Katib. Check the comment here: https://github.com/kubeflow/katib/pull/1426#issuecomment-775228644.
We can't add @DomFleischmann to the OWNERS list until we don't add him to the Kubeflow org.

Should we wait for the more contributions and update OWNERS file after or we can add him to the Kubeflow org now ?

/cc @RFMVasconcelos @gaocegege @johnugeorge

**Comment by terrytangyuan** [comment]
Got it. Welcome! I am fine with adding him now.

**Review by andreyvelich — COMMENTED** [review]
/ok-to-test
/lgtm
/cc @Bobgy

**Comment by Bobgy** [comment]
/approve
Sure, welcome to Kubeflow!

**Pull request merged**
