### PR TITLE
Add ElayAharoni as member to kubeflow-org

### LINKED ISSUE #697: Add ElayAharoni as member to kubeflow org
# Membership Request

Please read the [guidelines](https://www.kubeflow.org/docs/about/contributing/#joining-the-community) for joining the Kubeflow GitHub org before opening an issue

**Please provide links to PRs or other contributions (2-3):**
* https://github.com/kubeflow/pipelines/pull/11115
* https://github.com/kubeflow/website/pull/3820
* https://github.com/kubeflow/pipelines/pull/11060#issuecomment-2272953624
* https://github.com/kubeflow/pipelines/pull/11096

**Please list 2 existing members who are sponsoring your membership:**
@hbelmiro 
@HumairAK 

## Please test your PR

Run

```bash
cd github_orgs
pytest test_org_yaml.py
```

Include the output in the PR

## Additional Instructions

After your PR is merged please wait at least 1 hour for changes to propogate.

If after an hour you haven't recieved an invite to join the GitHub org please open an issue.

### PR DESCRIPTION
**Pull request by ElayAharoni**
Resolve #697 

Contributions:
* https://github.com/kubeflow/pipelines/pull/11115
* https://github.com/kubeflow/website/pull/3820
* https://github.com/kubeflow/pipelines/pull/11060#issuecomment-2272953624
* https://github.com/kubeflow/pipelines/pull/11096

pytest output:
image

### CODE REVIEW

**Comment by hbelmiro** [comment]
I'm happy to sponsor @ElayAharoni's membership.

/lgtm
/ok-to-test

**Comment by HumairAK** [comment]
Also happy to sponsor @ElayAharoni's membership.

/lgtm

**Comment by hbelmiro** [comment]
cc @terrytangyuan

**Review by terrytangyuan — APPROVED** [review]
Thanks!

/lgtm
/approve

**Comment by terrytangyuan** [comment]
@zijianjoy Could you help look into why the membership change is not effective? @ElayAharoni has not received the invite yet

**Comment by zijianjoy** [comment]
Looks like github is not happy about having people in both admin and member roles, created https://github.com/kubeflow/internal-acls/pull/704 to fix.

**Pull request merged**
