### PR TITLE
Adds ian coffey to test infra team list

### PR DESCRIPTION
**Pull request by iancoffey**
Requesting access so I can troubleshoot this broken examples situation.

https://github.com/kubeflow/examples/pull/795#issuecomment-629418401

### CODE REVIEW

**Comment by jlewi** [comment]
@iancoffey YOu only need viewer access for the logs. 
So please join
https://github.com/kubeflow/internal-acls/blob/master/ci-viewer.members.txt

**Comment by jlewi** [comment]
/ok-to-test

Can you also add yourself to the github org?

/assign @jlewi

**Comment by iancoffey** [comment]
@jlewi updated, thanks

**Pull request merged**
