### PR TITLE
Update org.yaml to be added as a member of pipeline team

### PR DESCRIPTION
**Pull request by animeshsingh**
Seems i need to be in the pipeline members team to be able to review and approve PRs

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/70)

### CODE REVIEW

**Comment by jlewi** [comment]
Why do you think that? Reviewing and approving PRs should be based on OWNERs files as described in the contributing guide.

**Comment by animeshsingh** [comment]
Well it has been a constant issue there. Even though OWNERS file has that listed in sub-directory its going to the top level OWNERS file.

**Comment by jlewi** [comment]
@animeshsingh Can you give me a specific example of a PR where an approver in a sub file was not able to approve something?

**Comment by animeshsingh** [comment]
Thanks - getting added to the org would be best. What do I need for that?

**Comment by animeshsingh** [comment]
btw this was the last one where we had issues
https://github.com/kubeflow/pipelines/pull/915#issuecomment-470704297

and many like this. Lets start with being added to the org, and then we can take forward from there

**Comment by jlewi** [comment]
Add yourself to the org here:
https://github.com/kubeflow/internal-acls/blob/cd7bc4997128b87f972c58f04b1cc70eb4a0d288/github-orgs/kubeflow/org.yaml#L29

Just add yourself as a member of the org not as a member of any teams.

Please insert yourself in alphabetical order.

**Comment by animeshsingh** [comment]
i am already there
https://github.com/kubeflow/internal-acls/blob/b55f6fd70bfbec078bad516059fe913a68d6c757/github-orgs/kubeflow/org.yaml#L31

But I dont see myself listed when I go to 
https://github.com/orgs/kubeflow/people

**Comment by jlewi** [comment]
The permissions need to be manually sync'd.
I just sync'd them.. So check your email for an invitation from GitHub to join the org and accept it.

Closing this PR because it shouldn't be necessary.

**Pull request closed without merging**
