### PR TITLE
Remove 'karkumar' from org.yaml

### LINKED ISSUE #344: Is the GitHub Sync Broken Again?
Looks like recent PRs may not have been sync'd.

For example #341 and #342 don't appear to have been sync'd.

@Bobgy @rmgogogo could on of you take a look please?

### PR DESCRIPTION
**Pull request by chensun**
To fix broken Github sync: "Configuration failed: failed to configure kubeflow members: all team members/maintainers must also be org members: karkumar"

Fixes #344

### CODE REVIEW

**Comment by jlewi** [comment]
@chensun So the problem is that we have team members who are not org members? Do we have an issue  tracking adding an appropriate presubmit test?

I think we want to remove all references to karkumar  so remove him from the google-team. perm #339 I don't think that's the actual GitHub account he wants to use.

**Comment by chensun** [comment]
> @chensun So the problem is that we have team members who are not org members? Do we have an issue tracking adding an appropriate presubmit test?
> 
> I think we want to remove all references to karkumar so remove him from the google-team. perm #339 I don't think that's the actual GitHub account he wants to use.

Thanks, Jeremy. I updated the change to remove `karkumar` instead. 
Also opened #346 and assigned @Bobgy @rmgogogo to follow up on the presubmit test.

**Pull request merged**
