### PR TITLE
Added svalleru to kubeflow org

### PR DESCRIPTION
**Pull request by svalleru**
Some contributions thus far:
https://github.com/kubeflow/kubeflow/pull/2241
https://github.com/kubeflow/kubeflow/pull/2305
https://github.com/kubeflow/kubeflow/pull/2314
https://github.com/kubeflow/testing/pull/285

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/internal-acls/51)

### CODE REVIEW

**Comment by abhi-g** [comment]
Please, also add yourself to https://github.com/kubeflow/community/blob/master/members.yaml

**Comment by svalleru** [comment]
> Please, also add yourself to https://github.com/kubeflow/community/blob/master/members.yaml

@abhi-g can you review https://github.com/kubeflow/community/pull/223 ?

**Pull request merged**
