### PR TITLE
Add kfserving repo into third-party-bots

### PR DESCRIPTION
**Pull request by PatrickXYS**
Since we have a blocking sync issue as described #361 ,

Move foward with kfserving repo.

/cc @jlewi

### CODE REVIEW

**Comment by jlewi** [comment]
It looks like the sync failed for kfctl
{"component":"peribolos","file":"prow/cmd/peribolos/main.go:201","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure kubeflow team third-party-bots-1321 repos: failed to update team 4230878(third-party-bots-1321) permissions on repo kfctl to write: status code 422 not one of [204], body: {\"message\":\"Validation Failed\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#add-or-update-team-repository-permissions\"}","time":"2020-11-02T21:50:24Z"}

Do you want to try removing kfctl and adding kfserving

**Comment by PatrickXYS** [comment]
Sure, let me do it this way 

@PatrickXYS

**Pull request merged**
