### PR TITLE
add deadeyegoodwin to org

### PR DESCRIPTION
**Pull request by deadeyegoodwin**

### CODE REVIEW

**Comment by Bobgy** [comment]
Can you please link your contributions to Kubeflow?

**Comment by deadeyegoodwin** [comment]
Led the design of the V2 dataplan protocols. https://github.com/kubeflow/kfserving/tree/master/docs/predict-api/v2

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you for your contributions! Welcome to Kubeflow

**Pull request merged**
