### PR TITLE
Add juliusvonkohout to wg-manifests-leads group

### PR DESCRIPTION
**Pull request by juliusvonkohout**
Over the last year i accumulated even more accepted PRs than i had at https://github.com/kubeflow/internal-acls/pull/509 and https://github.com/kubeflow/manifests/pull/2432. i am heavily engaged in the security and kuberay efforts. In addition i also mentored other contributors that now have accepted PRs. I would like to apply for membership to the wg-manifests-lead group.

@zijianjoy 
@Bobgy
@james-jwu
@chensun
@kimwnasptd
@annajung 

i have also created https://github.com/kubeflow/manifests/pull/2337 just to be sure

### CODE REVIEW

**Comment by jbottum** [comment]
Considering Julius' efforts and commitment, I think we should support his request and promotion.   I would like to know what it includes with respect to the https://github.com/kubeflow/manifests/blob/master/OWNERS and which title that Julius is applying for i.e. Sub Project Owner, https://github.com/kubeflow/community/blob/master/wgs/wg-governance.md

**Comment by juliusvonkohout** [comment]
@james-jwu @zijianjoy it is now aproved by the manifests WG lead Kimonas https://github.com/kubeflow/manifests/pull/2337#issuecomment-1823253395

**Comment by zijianjoy** [comment]
/lgtm
/approve

Thank you Julius for the contribution and congratulations on joining as manifests WG lead!

**Pull request merged**
