### PR TITLE
add denkensk as member

### PR DESCRIPTION
**Pull request by denkensk**
[6 PR merged in kubeflow/arena](https://github.com/kubeflow/arena/pulls?q=is%3Apr+is%3Aclosed+author%3Adenkensk+)

### CODE REVIEW

**Comment by zw0610** [comment]
/lgtm

Let's expand your effort and contribution from arena to other kubeflow projects.

**Comment by james-jwu** [comment]
Thank you for your contributions!
/lgtm
/approve

**Pull request merged**
