### PR TITLE
Add DharmitD as member

### PR DESCRIPTION
**Pull request by DharmitD**
Refer to https://github.com/kubeflow/internal-acls/issues/629

Contributed issues:
https://github.com/kubeflow/kfp-tekton/pull/1359
https://github.com/kubeflow/pipelines/pull/10269

pytest output:


```
(base) [ddalvi@localhost github-orgs]$ pytest test_org_yaml.py
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/ddalvi/kubeflow-community/internal-acls/github-orgs
collected 1 item                                                                                                                                                                                                                             

test_org_yaml.py .                                                                                                                                                                                                                     [100%]

============================================================================================================= 1 passed in 0.20s ==============================================================================================================
(base) [ddalvi@localhost github-orgs]$ 
```

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by zijianjoy** [comment]
/approve

Welcome to the community! @DharmitD

**Comment by DharmitD** [comment]
Thank you @terrytangyuan @Tomcli @zijianjoy !

**Pull request merged**
