### PR TITLE
Add in alexlatchford to Kubeflow contributors

### PR DESCRIPTION
**Pull request by alexlatchford**
Working with Kubeflow day-to-day now as a part of the ML platform team at Zillow Group, starting to make contributions to `kubeflow/pipelines` and really just want to be able to automatically kick off builds in CI without needing approvals 😅

### CODE REVIEW

**Comment by alexlatchford** [comment]
@googlebot I signed it!

**Comment by alexlatchford** [comment]
Ah looks like because I used the Github editor to produce the change it didn't set my email in the `git commit` and thus didn't sign the CLA, is this a blocker? See here for verification: https://github.com/kubeflow/pipelines/pull/4228#event-3555251381

Happy to reopen with a proper commit if so.

**Comment by Bobgy** [comment]
Your guesses are right. Please use a proper commit.

**Comment by Bobgy** [comment]
@alexlatchford thank you for your contributions to kubeflow/pipelines!

/lgtm
/approve

**Pull request merged**
