### PR TITLE
Add gmfrasca as member to kubeflow org

### PR DESCRIPTION
**Pull request by gmfrasca**
Implements #673 

/kind area/process

Please read the [guide lines](https://www.kubeflow.org/docs/about/contributing/#joining-the-community) for joining the Kubeflow GitHub org before opening an issue

**Please provide links to PRs or other contributions (2-3):**
https://github.com/kubeflow/kfp-tekton/pull/1259
https://github.com/kubeflow/pipelines/pull/10640
https://github.com/kubeflow/pipelines/pull/10568

** Please list 2 existing members who are sponsoring your membership:**
@rimolive && @HumairAK 

** Please test your PR **

Run

```
cd github_orgs
pytest test_org_yaml.py
```
Include the output in the PR

**Output**
```
(github-orgs) [gfrasca@dhcp137-14 github-orgs]$ pytest test_org_yaml.py 
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.10.13, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/gfrasca/src/internal-acls/github-orgs
collected 1 item                                                                                                                                                                                                                             

test_org_yaml.py .                                                                                                                                                                                                                     [100%]

============================================================================================================= 1 passed in 0.12s ==============================================================================================================
(github-orgs) [gfrasca@dhcp137-14 github-orgs]$
```

**Additional Instructions**

After your PR is merged please wait at least 1 hour for changes to propogate. 

If after an hour you haven't recieved an invite to join the GitHub org please open an issue.

You can contact build copy in #buildcop in kubeflow.slack.com

### CODE REVIEW

**Review by hbelmiro — COMMENTED** [review]
Happy to sponsor. Thanks for your contributions @gmfrasca.
/lgtm

**Comment by rimolive** [comment]
/lgtm

I'll be sponsoring Giulio as well.

**Comment by HumairAK** [comment]
happy to sponsort @gmfrasca

 /lgtm

**Review by terrytangyuan — APPROVED** [review]
Thanks. Merging.

/lgtm

**Pull request merged**
