### PR TITLE
add lampajr as member

### PR DESCRIPTION
**Pull request by lampajr**
**Read the [guidelines for joining the Kubeflow GitHub org](https://www.kubeflow.org/docs/about/contributing/#joining-the-community) before opening an issue.**

I confirm that

**Provide 2-3 links to PRs or other contributions.**
- Participated in manifests repo fixes for Kubeflow 1.9:
   - https://github.com/kubeflow/manifests/pull/2682
   - https://github.com/kubeflow/manifests/pull/2693
   - https://github.com/kubeflow/manifests/pull/2704
   - https://github.com/kubeflow/manifests/pull/2697
- Proposing test automation in this repo https://github.com/kubeflow/internal-acls/pull/678
- Participating in https://github.com/kubeflow/website/pull/3698
- Co-authored example https://github.com/kubeflow/examples/pull/1091
- One of the contributor of [Kubeflow Model Registry](https://github.com/kubeflow/model-registry)
- Created model registry example on Kserve website https://github.com/kserve/website/pull/346

**List 2 existing members who are sponsoring your membership.**
* @tarilabs 
* @rimolive 

**Test your PR by running the following:**
```bash
(internal-acls) alampare:github-orgs/ (add_lampajr) $ pytest test_org_yaml.py                                                                      [18:05:29]
==================================================================== test session starts =====================================================================
platform linux -- Python 3.10.14, pytest-8.2.0, pluggy-1.5.0
rootdir: /home/alampare/kubeflow/internal-acls/github-orgs
collected 1 item                                                                                                                                             

test_org_yaml.py .                                                                                                                                     [100%]

===================================================================== 1 passed in 0.15s ======================================================================
```

### CODE REVIEW

**Comment by hbelmiro** [comment]
/ok-to-test /lgtm
I'm happy to sponsor @lampajr's membership.

**Comment by tarilabs** [comment]
/lgtm

Thank you @lampajr for your contributions, happy to cosponsor membership

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
