### PR TITLE
Update org.yaml

### PR DESCRIPTION
**Pull request by aniruddhachoudhury**
Submitted the PR by adding name

### CODE REVIEW

**Comment by Bobgy** [comment]
/assign @jlewi 
What's our requirement for approving requests like this?

**Comment by aniruddhachoudhury** [comment]
> Hi @aniruddhachoudhury. Thanks for your PR.
> 
> I'm waiting for a [kubeflow](https://github.com/orgs/kubeflow/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/kubeflow/kubeflow/blob/master/CONTRIBUTING.md) to skip this step.
> 
> Once the patch is verified, the new status will be reflected by the `ok-to-test` label.
> 
> I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=kubeflow%2Finternal-acls).

Thanks @k8s-ci-robot  for that

**Comment by aniruddhachoudhury** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by:
> To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **theadactyl**
> You can assign the PR to them by writing `/assign @theadactyl` in a comment when ready.
> 
> The full list of commands accepted by this bot can be found [here](?repo=kubeflow%2Finternal-acls).
> 
> Needs approval from an approver in each of these files:
> * **[github-orgs/OWNERS](https://github.com/kubeflow/internal-acls/blob/master/github-orgs/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment
> Approvers can cancel approval by writing `/approve cancel` in a comment

/assign @theadactyl

**Comment by jlewi** [comment]
@aniruddhachoudhury  per https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org

Have you already submitted PRs to Kubeflow? If so could you link to them here?

**Comment by aniruddhachoudhury** [comment]
> @aniruddhachoudhury per https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org
> 
> Have you already submitted PRs to Kubeflow? If so could you link to them here?

Can you tell me that what PR describes ? Because i was trying to find out but didn't got that.

**Comment by jlewi** [comment]
PR = pull request; i.e. a change to the Kubeflow code base

**Pull request closed without merging**
