### PR TITLE
add gregsheremeta to kubeflow team and Red Hat org

### PR DESCRIPTION
**Pull request by gregsheremeta**
image

thanks

### CODE REVIEW

**Comment by hbelmiro** [comment]
I'm happy to sponsor @gregsheremeta membership.

/lgtm

**Review by DharmitD — COMMENTED** [review]
/lgtm

Welcome to the club @gregsheremeta !

**Comment by hbelmiro** [comment]
cc @terrytangyuan @andreyvelich

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Pull request merged**
