### PR TITLE
Update org.yaml

### PR DESCRIPTION
**Pull request by deepk2u**
**2-3 links to PRs or other contributions**
https://github.com/kubeflow/kubeflow/pull/6749
https://github.com/kubeflow/kubeflow/pull/6893
https://github.com/kubeflow/blog/pull/86

**2 existing members who are sponsoring your membership**
@jbottum 
@kimwnasptd 

**output of the PR build**
```
============================================================================================================================= test session starts ==============================================================================================================================
platform darwin -- Python 3.9.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/dkumar11/Documents/projects/internal-acls/github-orgs
collected 1 item

test_org_yaml.py .                                                                                                                                                                                                                                                       [100%]

============================================================================================================================== 1 passed in 0.19s ===============================================================================================================================
```

### CODE REVIEW

**Comment by zijianjoy** [comment]
Please follow https://github.com/kubeflow/internal-acls#joining-kubeflow-github-organization if you want to join Kubeflow org.

Please also remove the Intuit group as it is currently not needed for use in the kubeflow github org.

**Comment by deepk2u** [comment]
@zijianjoy Updated in the PR description.

**Comment by zijianjoy** [comment]
Thank you @deepk2u ! I will wait for @jbottum and @kimwnasptd for the comment.

**Comment by jbottum** [comment]
/lgtm

@kimwnasptd please review

**Comment by kimwnasptd** [comment]
/lgtm

Thanks for your contributions @deepk2u!

**Comment by zijianjoy** [comment]
/lgtm
/approve

Welcome to the community! @deepk2u

**Pull request merged**
