### PR TITLE
adding tarekabouzeid to kubeflow org

### PR DESCRIPTION
**Pull request by tarekabouzeid**
Contributions and discussions:

- https://github.com/kubeflow/manifests/pull/2872
- https://github.com/kubeflow/manifests/pull/2864

Sponsors:

- @juliusvonkohout 
- @rimolive 
can you please sponsor my membership ?

Test:
```bash
================================== test session starts ===================================
platform linux -- Python 3.11.9, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/tarek/git_local/kubeflow_os/kubeflow-internal-acls/github-orgs
plugins: anyio-4.4.0
collected 1 item                                            

test_org_yaml.py .                                                                 [100%]

=================================== 1 passed in 0.10s ====================================
```

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
cc @andreyvelich

**Review by andreyvelich — COMMENTED** [review]
Thank you for your contributions @tarekabouzeid 🎉 
/lgtm
/approve

**Pull request merged**
