### PR TITLE
Request join to Kubeflow org

### PR DESCRIPTION
**Pull request by kuizhiqing**
Plz consider my request for continuing support.

### CODE REVIEW

**Comment by kuizhiqing** [comment]
@johnugeorge plz help with this, thx.

**Comment by johnugeorge** [comment]
+1 
@kuizhiqing has added Paddlepaddle support to training operator https://github.com/kubeflow/training-operator/pull/1675 and https://github.com/kubeflow/website/pull/3388

Thanks for all contributions

/lgtm

**Comment by johnugeorge** [comment]
/lgtm cancel

Can you remove the entry from wg-training leads section ? You have to add as an reviewer in https://github.com/kubeflow/training-operator/blob/master/OWNERS

**Review by terrytangyuan — COMMENTED** [review]
+1 to add as a member. Please address @johnugeorge's comment above

**Comment by kuizhiqing** [comment]
Done.
Thanks @johnugeorge @terrytangyuan

**Review by andreyvelich — COMMENTED** [review]
/assign @chensun @james-jwu @neuromage @zijianjoy

**Pull request merged**
