### PR TITLE
remove myself from repo owner so that bob can be well routed.

### PR DESCRIPTION
**Pull request by rmgogogo**

### CODE REVIEW

**Comment by rmgogogo** [comment]
@Bobgy would you help issue the PRs?
I has the CLA problem due to using my current company's profile.

Thanks.

**Comment by rmgogogo** [comment]
> @Bobgy would you help issue the PRs?
> I has the CLA problem due to using my current company's profile.
> 
> Thanks.

other repos:
kubeflow/pipelines
kubeflow/website
kubeflow/testing
etc. which contains me as OWNER

**Comment by jlewi** [comment]
@Bobgy You should be able to manually change the label on the issue to "cla: yes" to make the CLA check pass.

**Comment by Bobgy** [comment]
/lgtm
/approve
Thanks

**Pull request merged**
