### PR TITLE
Add droctothorpe as member

### PR DESCRIPTION
**Pull request by droctothorpe**
Closed [this issue](https://github.com/kubeflow/internal-acls/issues/656) in favor of this PR. There are some conflicting instructions on the website vs the readme here / community repo.

**Please provide links to PRs or other contributions (2-3):**
- https://github.com/kubeflow/pipelines/pull/10471
- https://github.com/kubeflow/katib/pull/2183
- https://github.com/kubeflow/pipelines/pull/8517

** Please list 2 existing members who are sponsoring your membership:**
@connor-mccarthy 
@andreyvelich 

** Please test your PR **

Run

```
cd github_orgs
pytest test_org_yaml.py
```
Include the output in the PR
```
===================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.11.4, pytest-7.4.3, pluggy-1.0.0
rootdir: /Users/inn487/code/kubeflow/internal-acls/github-orgs
plugins: anyio-4.0.0, cov-4.1.0
collected 1 item

test_org_yaml.py .                                                                                                                                                                      [100%]

====================================================================================== 1 passed in 0.11s ======================================================================================
```

### CODE REVIEW

**Review by andreyvelich — APPROVED** [review]
/lgtm
Thanks again for all of your great contributions @droctothorpe 🎉 
/assign @james-jwu @zijianjoy

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by droctothorpe** [comment]
> @droctothorpe Please sign your commit for DCO.

Thanks, @andreyvelich. Fixed! 👍

**Comment by andreyvelich** [comment]
Great, thanks @droctothorpe!
/lgtm
/approve

**Pull request merged**
