### PR TITLE
adding name as new member

### PR DESCRIPTION
**Pull request by sulabh2000**
I want to join the Kubeflow community and make contributions to it.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Please share a link to your contributions so far.

**Comment by sulabh2000** [comment]
> Please share a link to your contributions so far.



> Please share a link to your contributions so far.

I am starting as a new member/contributor to this community so I haven't made any contributions towards Kubeflow. Also in your documentation, it is mentioned that we need to first add ourselves to org.yaml file to start contributions.
If it's not the case then I will first make contributions and then apply for it.
Thankyou.

**Comment by Bobgy** [comment]
No, anyone can contribute, adding to the org makes contribution experience better, but it's not a requirement.

It seems updating that doc can be a good contribution too

**Comment by sulabh2000** [comment]
> No, anyone can contribute, adding to the org makes contribution experience better, but it's not a requirement.
> 
> It seems updating that doc can be a good contribution too

yep..will definitely update that doc.

**Pull request closed without merging**
